### ISSUE TITLE
When trying to convert from task to event, command should remain in prompt

### ISSUE THREAD

**Issue by karen** [CS2103AUG2016-W10-C2/main#94]
`edit 1 start/1pm end/2pm` -> User receives prompt to delete/add instead, but command prompt is cleared. Would be nice if the command stays and the user does not need to retype.

i.e. Should raise an incorrect command event.

**Comment by tjonganthony** [comment]
Since we asked the user to delete and add, wouldn't it be better to clear the command to make it easier for user to delete?

I created PR #124 just in case youu still want it.

**Comment by karen** [comment]
I felt that since the user had already typed `edit start/<time> end/<time>` they can just go to the start of the line and change it to `add` and fill up a title instead of retyping all the flags (including potentially `desc` and `#tags`). What do you think?

Deleting the old deadline would be pretty easy after adding the new event since it only requires an index.

**Comment by joeleba** [comment]
perhaps we can have a way for users to cycle through their previous inputs? Something like pressing the "up" button on command line

**Comment by karen** [comment]
That'd definitely be a useful feature to have.
